# Generated by Django 4.2.4 on 2023-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
