# Generated by Django 3.2.15 on 2023-08-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phon_number', models.ImageField(upload_to='')),
                ('membershipـtype', models.CharField(choices=[('special', 'ویژه'), ('Normal', 'عادی')], default=[1], max_length=30)),
                ('Membership_validity_date', models.DateField()),
                ('Membership_expiration_date', models.DateField()),
            ],
        ),
    ]
