# Generated by Django 4.2.4 on 2023-08-26 11:50

from django.db import migrations, models
import user_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='channel',
            field=models.CharField(choices=[('Phone', 'Phone')], default='Phone', max_length=10),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=user_accounts.models.generate_otp, max_length=4),
        ),
    ]
