# Generated by Django 4.2.4 on 2023-08-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_rename_usermodel_user_alter_otprequest_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='first_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='last_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='pass_one',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='pass_two',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
