# Generated by Django 4.2.4 on 2023-08-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_otprequest_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('ویژه', 'Special'), ('ساده', 'Simple')], default='ساده', max_length=10)),
                ('number_day', models.IntegerField(choices=[(31, 'Special'), (0, 'Default')], default=0)),
                ('date_time', models.DateTimeField()),
                ('Membership_validity_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.user')),
            ],
        ),
    ]
