# Generated by Django 4.2.4 on 2023-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_accounnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_breaker_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_service', models.CharField(choices=[('kavengar', 'Kavengar'), ('signal', 'Signal')], default='kavengar', max_length=25)),
            ],
        ),
    ]
